2025-03-18 15:29:27 - ERROR - api:612 - Error rendering settings page: block 'page_css' defined twice
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\ui\pages.py", line 598, in settings
    return templates.TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 40, in __init__
    content = template.render(context)
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "K:\anita\poc\frontend\templates\settings.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "K:\anita\poc\frontend\templates\base.html", line 17, in template
    {% block page_css %}{% endblock %}
jinja2.exceptions.TemplateAssertionError: block 'page_css' defined twice
2025-03-18 15:46:39 - ERROR - api:544 - Error rendering MIFARE page: block 'page_title' defined twice
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\ui\pages.py", line 533, in mifare
    return templates.TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 208, in TemplateResponse
    template = self.get_template(name)
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 131, in get_template
    return self.env.get_template(name)
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 1016, in get_template
    return self._load_template(name, globals)
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 975, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "K:\anita\poc\venv\lib\site-packages\jinja2\loaders.py", line 138, in load
    code = environment.compile(source, name, filename)
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 771, in compile
    self.handle_exception(source=source_hint)
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "K:\anita\poc\frontend\templates\mifare.html", line 18, in template
    {% block page_title %}MIFARE Card Management{% endblock %}
jinja2.exceptions.TemplateAssertionError: block 'page_title' defined twice
2025-03-18 23:11:01 - ERROR - api:612 - Error rendering settings page: Encountered unknown tag 'now'. Jinja was looking for the following tags: 'endmacro'. The innermost block that needs to be closed is 'macro'.
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\ui\pages.py", line 598, in settings
    return templates.TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 40, in __init__
    content = template.render(context)
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "K:\anita\poc\frontend\templates\settings.html", line 3, in top-level template code
    {% from "components/toggle_control.html" import render_toggle, render_toggle_group %}
  File "K:\anita\poc\frontend\templates\base.html", line 47, in top-level template code
    {% from "components/footer.html" import render_footer %}
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "K:\anita\poc\frontend\templates\components\footer.html", line 10, in template
    &copy; {% now 'Y' %} ANITA | Advanced NFC, Identification & Technology Authentication Solutions
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'now'. Jinja was looking for the following tags: 'endmacro'. The innermost block that needs to be closed is 'macro'.
2025-03-18 23:11:11 - ERROR - api:612 - Error rendering settings page: Encountered unknown tag 'now'. Jinja was looking for the following tags: 'endmacro'. The innermost block that needs to be closed is 'macro'.
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\ui\pages.py", line 598, in settings
    return templates.TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 40, in __init__
    content = template.render(context)
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "K:\anita\poc\frontend\templates\settings.html", line 3, in top-level template code
    {% from "components/toggle_control.html" import render_toggle, render_toggle_group %}
  File "K:\anita\poc\frontend\templates\base.html", line 47, in top-level template code
    {% from "components/footer.html" import render_footer %}
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "K:\anita\poc\frontend\templates\components\footer.html", line 10, in template
    &copy; {% now 'Y' %} ANITA | Advanced NFC, Identification & Technology Authentication Solutions
jinja2.exceptions.TemplateSyntaxError: Encountered unknown tag 'now'. Jinja was looking for the following tags: 'endmacro'. The innermost block that needs to be closed is 'macro'.
2025-03-18 23:15:23 - ERROR - api:612 - Error rendering settings page: 'now' is undefined
Traceback (most recent call last):
  File "K:\anita\poc\backend\routes\ui\pages.py", line 598, in settings
    return templates.TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 209, in TemplateResponse
    return _TemplateResponse(
  File "K:\anita\poc\venv\lib\site-packages\starlette\templating.py", line 40, in __init__
    content = template.render(context)
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 1295, in render
    self.environment.handle_exception()
  File "K:\anita\poc\venv\lib\site-packages\jinja2\environment.py", line 942, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "K:\anita\poc\frontend\templates\settings.html", line 3, in top-level template code
    {% from "components/toggle_control.html" import render_toggle, render_toggle_group %}
  File "K:\anita\poc\frontend\templates\base.html", line 48, in top-level template code
    {{ render_footer() }}
  File "K:\anita\poc\venv\lib\site-packages\jinja2\runtime.py", line 784, in _invoke
    rv = self._func(*arguments)
  File "K:\anita\poc\frontend\templates\components\footer.html", line 10, in template
    &copy; {{ now().year }} ANITA | Advanced NFC, Identification & Technology Authentication Solutions
  File "K:\anita\poc\venv\lib\site-packages\jinja2\utils.py", line 92, in from_obj
    if hasattr(obj, "jinja_pass_arg"):
jinja2.exceptions.UndefinedError: 'now' is undefined
